using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace DeepBot.Data.Model
{
    #region Etat character enum 
    public enum CharacterState
    {
        DISCONNECTED = 0,
        CONNECTING = 1,
        IDLE = 2,
        WALKING = 3,
        GATHERING = 4,
        FIGHTING = 5,
        DIALOGING = 6
    }
    #endregion

    #region Type item enum
    public enum ItemTypeEnum
    {
        TYPE_AMULETTE = 1,
        TYPE_ARC = 2,
        TYPE_BAGUETTE = 3,
        TYPE_BATON = 4,
        TYPE_DAGUES = 5,
        TYPE_EPEE = 6,
        TYPE_MARTEAU = 7,
        TYPE_PELLE = 8,
        TYPE_ANNEAU = 9,
        TYPE_CEINTURE = 10,
        TYPE_BOTTES = 11,
        TYPE_POTION = 12,
        TYPE_APRCHO_EXP = 13,
        TYPE_DONS = 14,
        TYPE_RESSOURCE = 15,
        TYPE_COIFFE = 16,
        TYPE_CAPE = 17,
        TYPE_FAMILIER = 18,
        TYPE_HACHE = 19,
        TYPE_OUTIL = 20,
        TYPE_PIOCHE = 21,
        TYPE_FAUX = 22,
        TYPE_DOFUS = 23,
        TYPE_QUETES = 24,
        TYPE_DOCUMENT = 25,
        TYPE_FM_POTION = 26,
        TYPE_TRANSFORM = 27,
        TYPE_BOOST_FOOD = 28,
        TYPE_BENEDICTION = 29,
        TYPE_MALEDICTION = 30,
        TYPE_RP_BUFF = 31,
        TYPE_PERSO_SUIVEUR = 32,
        TYPE_PAIN = 33,
        TYPE_CEREALE = 34,
        TYPE_FLEUR = 35,
        TYPE_PLANTE = 36,
        TYPE_BIERE = 37,
        TYPE_BOIS = 38,
        TYPE_MINERAIS = 39,
        TYPE_ALLIAGE = 40,
        TYPE_POISSON = 41,
        TYPE_BONBON = 42,
        TYPE_POTION_OUBLIE = 43,
        TYPE_POTION_METIER = 44,
        TYPE_POTION_SORT = 45,
        TYPE_FRUIT = 46,
        TYPE_OS = 47,
        TYPE_POUDRE = 48,
        TYPE_COMESTI_POISSON = 49,
        TYPE_PIERRE_PRECIEUSE = 50,
        TYPE_PIERRE_BRUTE = 51,
        TYPE_FARINE = 52,
        TYPE_PLUME = 53,
        TYPE_POIL = 54,
        TYPE_ETOFFE = 55,
        TYPE_CUIR = 56,
        TYPE_LAINE = 57,
        TYPE_GRAINE = 58,
        TYPE_Peau = 59,
        TYPE_HUILE = 60,
        TYPE_PELUCHE = 61,
        TYPE_POISSON_VIDE = 62,
        TYPE_VIANDE = 63,
        TYPE_VIANDE_CONSERVEE = 64,
        TYPE_QUEUE = 65,
        TYPE_METARIA = 66,
        TYPE_LEGUME = 68,
        TYPE_VIANDE_COMESTIBLE = 69,
        TYPE_TEINTURE = 70,
        TYPE_EQUIP_ALCHIMIE = 71,
        TYPE_OEUF_FAMILIER = 72,
        TYPE_MAITRISE = 73,
        TYPE_FEE_ARTIFICE = 74,
        TYPE_APRCHEMIN_SORT = 75,
        TYPE_APRCHEMIN_CARAC = 76,
        TYPE_CERTIFICAT_CHANIL = 77,
        TYPE_RUNE_FORGEMAGIE = 78,
        TYPE_BOISSON = 79,
        TYPE_OBJET_MISSION = 80,
        TYPE_SAC_DOS = 81,
        TYPE_BOUCLIER = 82,
        TYPE_PIERRE_AME = 83,
        TYPE_CLEFS = 84,
        TYPE_PIERRE_AME_PLEINE = 85,
        TYPE_POPO_OUBLI_PERCEP = 86,
        TYPE_APRCHO_RECHERCHE = 87,
        TYPE_PIERRE_MAGIQUE = 88,
        TYPE_CADEAUX = 89,
        TYPE_FANTOME_FAMILIER = 90,
        TYPE_DRAGODINDE = 91,
        TYPE_BOUFTOU = 92,
        TYPE_OBJET_ELEVAGE = 93,
        TYPE_OBJET_UTILISABLE = 94,
        TYPE_PLANCHE = 95,
        TYPE_ECORCE = 96,
        TYPE_CERTIF_MONTURE = 97,
        TYPE_RACINE = 98,
        TYPE_FILET_CAPTURE = 99,
        TYPE_SAC_RESSOURCE = 100,
        TYPE_ARBALETE = 102,
        TYPE_APTTE = 103,
        TYPE_AILE = 104,
        TYPE_OEUF = 105,
        TYPE_OREILLE = 106,
        TYPE_CARAAPCE = 107,
        TYPE_BOURGEON = 108,
        TYPE_OEIL = 109,
        TYPE_GELEE = 110,
        TYPE_COQUILLE = 111,
        TYPE_PRISME = 112,
        TYPE_OBJET_VIVANT = 113,
        TYPE_ARME_MAGIQUE = 114,
        TYPE_FRAGM_AME_SHUSHU = 115,
        TYPE_POTION_FAMILIER = 116,
    }
    #endregion

    #region Type slot enum
    public enum ItemSlotEnum
    {
        SLOT_INVENTORY = -1,
        SLOT_AMULET = 0,
        SLOT_WEAPON = 1,
        SLOT_LEFT_RING = 2,
        SLOT_BELT = 3,
        SLOT_RIGHT_RING = 4,
        SLOT_BOOTS = 5,
        SLOT_HAT = 6,
        SLOT_CAPE = 7,
        SLOT_PET = 8,
        SLOT_DOFUS_1 = 9,
        SLOT_DOFUS_2 = 10,
        SLOT_DOFUS_3 = 11,
        SLOT_DOFUS_4 = 12,
        SLOT_DOFUS_5 = 13,
        SLOT_DOFUS_6 = 14,
        SLOT_SHIELD = 15,
        SLOT_MOUNT = 16,

        SLOT_BOOST_MUTATION = 20,
        SLOT_BOOST_FOOD = 21,
        SLOT_BOOST_BENEDICTION = 22,
        SLOT_BOOST_BENEDICTION_1 = 23,
        SLOT_BOOST_MALEDICTION = 24,
        SLOT_BOOST_MALEDICTION_1 = 25,
        SLOT_BOOST_ROLEPLAY_BUFF = 26,
        SLOT_BOOST_FOLLOWER = 27,

        SLOT_ITEMBAR_1 = 35,
        SLOT_ITEMBAR_2 = 36,
        SLOT_ITEMBAR_3 = 37,
        SLOT_ITEMBAR_4 = 38,
        SLOT_ITEMBAR_5 = 39,
        SLOT_ITEMBAR_6 = 40,
        SLOT_ITEMBAR_7 = 41,
        SLOT_ITEMBAR_8 = 42,
        SLOT_ITEMBAR_9 = 43,
        SLOT_ITEMBAR_10 = 44,
        SLOT_ITEMBAR_11 = 45,
        SLOT_ITEMBAR_12 = 46,
        SLOT_ITEMBAR_13 = 47,
        SLOT_ITEMBAR_14 = 48,
    }
    #endregion

    #region Type effet List
    public enum EffectEnum : int
    {
        None = -1,

        // Armures
        AddArmorNeutral = -2,
        AddArmorEarth = -3,
        AddArmorFire = -4,
        AddArmorWater = -5,
        AddArmorAir = -6,

        Teleport = 4,
        PushBack = 5,
        PushFront = 6,
        Transpose = 8,
        Evasion = 9,
        DamageBrut = -7,

        TurnPass = 140,

        MPSteal = 77,
        MPBonus = 78,
        EcaflipChance = 79,
        LifeSteal = 82,
        APSteal = 84,
        ChanceSteal = 266,
        VitalitySteal = 267,
        AgilitySteal = 268,
        IntelligenceSteal = 269,
        WisdomSteal = 270,
        StrengthSteal = 271,

        DamageLifeWater = 85,
        DamageLifeEarth = 86,
        DamageLifeAir = 87,
        DamageLifeFire = 88,
        DamageLifeNeutral = 89,
        DamageDropLife = 90,
        StealWater = 91,
        StealEarth = 92,
        StealAir = 93,
        StealFire = 94,
        StealNeutral = 95,
        DamageWater = 96,
        DamageEarth = 97,
        DamageAir = 98,
        DamageFire = 99,
        DamageNeutral = 100,
        AddArmor = 105,
        AddArmorBis = 265,

        AddReflectDamageItem = 220,
        ReflectSpell = 106,
        AddReflectDamage = 107,
        Heal = 108,
        SelfDamage = 109,
        AddLife = 110,
        AddAP = 111,
        AddDamage = 112,
        MultiplyDamage = 114,

        AddAPBis = 120,
        AddAgility = 119,
        AddChance = 123,
        AddDamagePercent = 138,
        SubDamagePercent = 186,
        AddDamageCritic = 115,
        AddDamagePiege = 225,
        //AddDamagePiegePercent = 225,
        AddDamagePhysic = 142,
        AddDamageMagic = 143,
        AddEchecCritic = 122,
        AddAPDodge = 160,
        AddMPDodge = 161,
        AddStrength = 118,
        AddInitiative = 174,
        AddIntelligence = 126,
        AddInvocationMax = 182,
        AddMP = 128,
        AddPO = 117,
        AddPods = 158,
        AddProspection = 176,
        AddWisdom = 124,
        AddHealCare = 178,
        AddVitality = 125,
        SubAgility = 154,

        DamagePerAP = 131,
        IncreaseSpellDamage = 293,
        Mastery = 165,
        POSteal = 320,
        Punition = 672,
        Sacrifice = 765,

        SubChance = 152,
        SubDamage = 164,
        SubDamageCritic = 171,
        SubDamageMagic = 172,
        SubDamagePhysic = 173,
        SubAPDodge = 162,
        SubMPDodge = 163,
        SubStrength = 157,
        SubInitiative = 175,
        SubIntelligence = 155,
        SubAPDodgeable = 101,
        SubMPDodgeable = 127,
        SubAP = 168,
        SubMP = 169,
        SubPO = 116,
        SubPods = 159,
        SubProspection = 177,
        SubWisdom = 156,
        SubHealCare = 179,
        SubVitality = 153,

        InvocDouble = 180,
        Invocation = 181,
        InvocationStatic = 185,

        AddReduceDamagePhysic = 183,
        AddReduceDamageMagic = 184,

        AddReduceDamagePercentWater = 211,
        AddReduceDamagePercentEarth = 210,
        AddReduceDamagePercentAir = 212,
        AddReduceDamagePercentFire = 213,
        AddReduceDamagePercentNeutral = 214,
        AddReduceDamagePercentPvPWater = 251,
        AddReduceDamagePercentPvPEarth = 250,
        AddReduceDamagePercentPvPAir = 252,
        AddReduceDamagePercentPvPFire = 253,
        AddReduceDamagePercentPvPNeutral = 254,

        AddReduceDamageWater = 241,
        AddReduceDamageEarth = 240,
        AddReduceDamageAir = 242,
        AddReduceDamageFire = 243,
        AddReduceDamageNeutral = 244,
        AddReduceDamagePvPWater = 261,
        AddReduceDamagePvPEarth = 260,
        AddReduceDamagePvPAir = 262,
        AddReduceDamagePvPFire = 263,
        AddReduceDamagePvPNeutral = 264,

        SubReduceDamagePercentWater = 216,
        SubReduceDamagePercentEarth = 215,
        SubReduceDamagePercentAir = 217,
        SubReduceDamagePercentFire = 218,
        SubReduceDamagePercentNeutral = 219,
        SubReduceDamagePercentPvPWater = 255,
        SubReduceDamagePercentPvPEarth = 256,
        SubReduceDamagePercentPvPAir = 257,
        SubReduceDamagePercentPvPFire = 258,
        SubReduceDamagePercentPvpNeutral = 259,
        SubReduceDamageWater = 246,
        SubReduceDamageEarth = 245,
        SubReduceDamageAir = 247,
        SubReduceDamageFire = 248,
        SubReduceDamageNeutral = 249,

        PandaCarrier = 50,
        PandaLaunch = 51,
        Perception = 202,
        ChangeSkin = 149,
        SpellBoost = 293,
        UseTrap = 400,
        UseGlyph = 401,
        DoNothing = 666,
        PushFear = 783,
        AddChatiment = 788,
        AddState = 950,
        RemoveState = 951,
        Stealth = 150,
        DeleteAllBonus = 132,

        /* Potion rappel */
        TeleportSavedZaap = 600,

        /* Parchemins */
        AddJob = 603,
        AddSpell = 604,
        AddExperience = 605,
        AddCaractStrength = 607,
        AddCaractWisdom = 678,
        AddCaractChance = 608,
        AddCaractAgility = 609,
        AddCaractVitality = 610,
        AddCaractIntelligence = 611,
        AddCaractPoint = 612,
        AddSpellPoint = 613,

        /* Gateaux */
        AddEnergy = 139,

        /* Bourses */
        AddKamas = 194,

        /* Bonbons boosts combats */
        AddBoost = 811,

        InvocationInformations = 628,

        SoulStoneStats = 705,
        MountCaptureProba = 706,

        SoulCaptureBonus = 750,
        MountExpBonus = 751,

        RenameGuild = 725,


        LastEat = 808,

        LaunchFight = 905,

        AlignmentChange = 188,
        AlignmentId = 960,
        AlignmentGrade = 961,
        TargetLevel = 962,
        CreateTime = 963,
        TargetName = 964,

        LivingGfxId = 970,
        LivingMood = 971,
        LivingSkin = 972,
        LivingType = 973,
        LivingXp = 974,

        CanBeExchange = 983,
        MadeBy = 988,
        Owner = 987,
        MountOwner = 996,
        Name = 997,

        /* ACTION SPECIALES BDD SCRIPT */
        BddDialogReply = 2000,
        BddDialogLeave = 2001,
        BddOpenBank = 2002,
        BddAddStatistic = 2003,
        BddAddItem = 2004,
        BddTeleport = 2005,
        BddResetStats = 2006,
        BddResetSpells = 2007,
        BddAddJob = 2008,
        BddRemoveItem = 2009,
        BddCreateGuild = 2010,
        BddLaunchFight = 2011,
    }
    #endregion

    #region Cell type enum
    public enum CellTypes
    {
        NOT_WALKABLE = 0,
        INTERACTIVE_OBJECT = 1,
        TELEPORT_CELL = 2,
        UNKNOWN1 = 3,
        WALKABLE = 4,
        UNKNOWN2 = 5,
        PATH_1 = 6,
        PATH_2 = 7
    }
    #endregion

    #region Movement direction enum
    public enum MovementDirection
    {
        NONE,
        TOP,
        BOTTOM,
        LEFT,
        RIGHT,
    }
    #endregion

    #region Classe
    public enum Classe
    {
        Cra  =0,
        Enutrof =1,
        Osamodas = 2,
        Iop = 3,
        Xelor = 4,
    }

    #endregion
}
